//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorioPersonas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int TelefonoID { get; set; }
        public string Numero { get; set; }
        public int PersonaID { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
